name: Embed code

on:
  push:
    branches:
      - master

jobs:
  embed-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: false
          fetch-depth: 0
          ref: master

      - name: git-setup
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: embedding-phase
        run: |
          npm install -g embedme
          find -type f -name '*.md' -exec embedme {} \;

      - name: embedding-phase
        run: |
          npm install -g embedme
          find -type f -name '*.md' -exec embedme {} \;

      - name: building
        run: |
          curl -sL 'https://github.com/rust-lang/mdBook/releases/download/v0.4.13/mdbook-v0.4.13-x86_64-unknown-linux-gnu.tar.gz' | tar xz
          ./mdbook build
          ls | grep -v book | xargs rm -rf
          mv book/* .
          rm -rf book

      - name: git-commit
        run: |
          git add *
          git commit -m "Embed code"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: github-pages
          force: true
